navigation:
  slam:
    algorithm: "cartographer"  # or "orb_slam", "rtab_map"
    mode: "2d"  # or "3d"

    parameters:
      map_resolution: 0.05  # meters per pixel
      update_frequency: 10  # Hz
      min_range: 0.3  # meters
      max_range: 10.0  # meters

  path_planning:
    algorithm: "navfn"  # or "global_planner", "smac_planner"
    local_planner: "dwa_local_planner"  # or "teb_local_planner"

    parameters:
      planning_frequency: 5  # Hz
      controller_frequency: 10  # Hz
      max_vel_x: 2.0  # m/s
      max_vel_theta: 1.0  # rad/s

  localization:
    use_ekf: true
    ekf_frequency: 30  # Hz

    sensors:
      odom0: "/mavros/local_position/odom"
      imu0: "/mavros/imu/data"
      pose0: "/camera/pose"  # if available
