sensors:
  camera:
    type: "camera"
    model: "usb_camera"  # or "realsense_d435i"
    enabled: true
    topics:
      color: "/camera/color/image_raw"
      info: "/camera/color/camera_info"
    frame_id: "camera_link"
    parameters:
      resolution: [640, 480]
      framerate: 30
      auto_exposure: true

  imu:
    type: "imu"
    model: "builtin"
    enabled: true
    topic: "/mavros/imu/data"
    frame_id: "base_link"
    parameters:
      update_rate: 100  # Hz

  # Optional sensors (disabled by default)
  lidar:
    enabled: false
    type: "lidar"
    model: "rplidar_a2"
    topic: "/scan"

  depth_camera:
    enabled: false
    type: "depth_camera"
    model: "realsense_d435i"
