drone:
  type: "mavros"
  platform: "px4"
  frame_type: "quadcopter"

  # Physical specifications
  specifications:
    mass: 1.5  # kg
    max_velocity: 5.0  # m/s
    max_acceleration: 3.0  # m/s²
    max_yaw_rate: 90  # deg/s
    max_altitude: 10.0  # m
    flight_time: 25  # minutes

  # Connection settings
  connection:
    type: "serial"  # or "udp", "tcp"
    port: "/dev/ttyACM0"
    baudrate: 57600

  # Flight modes
  flight_modes:
    takeoff: "GUIDED"
    navigation: "GUIDED"
    landing: "LAND"
    emergency: "LAND"

  # Safety limits
  safety:
    max_tilt_angle: 30  # degrees
    min_battery_voltage: 14.0  # volts
    max_wind_speed: 8  # m/s
    geofence_enabled: true
    geofence_radius: 100  # meters
