MAP_BUILDER = {
  use_trajectory_builder_2d = false,
  use_trajectory_builder_3d = false,
  num_background_threads = 4,
  pose_graph = {
    optimize_every_n_nodes = 90,
    constraint_builder = {
      sampling_ratio = 0.3,
      max_constraint_distance = 15.,
      min_score = 0.55,
      global_localization_min_score = 0.6,
      loop_closure_translation_weight = 1.1e4,
      loop_closure_rotation_weight = 1e5,
      log_matches = true,
      fast_correlative_scan_matcher = {
        linear_search_window = 7.,
        angular_search_window = math.rad(30.),
        branch_and_bound_depth = 7,
      },
      ceres_scan_matcher = {
        occupied_space_weight = 1.,
        translation_weight = 10.,
        rotation_weight = 40.,
        ceres_solver_options = {
          use_nonmonotonic_steps = false,
          max_num_iterations = 20,
          num_threads = 1,
        },
      },
    },
    matcher_translation_weight = 5e2,
    matcher_rotation_weight = 1.6e3,
    optimization_problem = {
      huber_scale = 1e1,
      acceleration_weight = 1e3,
      rotation_weight = 3e5,
      local_slam_pose_translation_weight = 1e5,
      local_slam_pose_rotation_weight = 1e5,
      odometry_translation_weight = 1e5,
      odometry_rotation_weight = 1e5,
      fixed_frame_pose_translation_weight = 1e1,
      fixed_frame_pose_rotation_weight = 1e2,
      log_solver_summary = false,
      ceres_solver_options = {
        use_nonmonotonic_steps = false,
        max_num_iterations = 50,
        num_threads = 7,
      },
    },
    max_num_final_iterations = 200,
    global_sampling_ratio = 0.003,
    log_residual_histograms = true,
    global_constraint_search_after_n_seconds = 10.,
  },
}
