ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        sensor_timeout: 0.1
        two_d_mode: false # Changed to false for 3D drone flight
        transform_time_offset: 0.0
        transform_timeout: 0.0
        print_diagnostics: true
        debug: false

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        # Visual Odometry from MAVROS (e.g., from a T265 camera)
        odom0: /mavros/odometry/in
        odom0_config:
            [true,  true,  true,
             false, false, false,
             false, false, false,
             false, false, false,
             false, false, false]
        odom0_differential: false

        # IMU data from the flight controller
        imu0: /mavros/imu/data
        imu0_config:
            [false, false, false,
             true,  true,  true,
             false, false, false,
             true,  true,  true,
             true,  true,  true]
        imu0_differential: false
        imu0_remove_gravitational_acceleration: true
